const
    Strings = {
        splashScreen: "Splash Screen",
        logIn: "Log In",
        register: "Register",
        forgotPassword: "Forgot password",
        verifyPassword: "Verify password",
        email:"Email",
        phone: "Phone number",
        name: "Name",
        plhEnterRating: "Enter rating",
        plhEnterName: "Enter name",
        plhEnterEmail: "Enter email",
        plhEnterPass: "Enter password",
        plhEnterPassAgain: "Enter password again",
        plhEnterPhone: "Enter phone number",
        plhSendVerifyCode: "Send verify code",
        plhSendNewPass: "Send new password",
        plhTypeHJere: "Type Here...",
        signUp: "SIGN UP",
        mainTabNavigation: "Main tab navigation",
        home: "Home",
        download: "Download",
        favorite: "Favorite",
        browse: "Browse",
        search: "Search",
        courses: "Courses",
        profile: "Profile",
        settings: "Settings",
        sendFeedback: "sendFeedback",
        recommendation: "Recommendation",
        sectionListCourse: "List course",
        category: "Category",
        skills: "Skills",
        paths: "Paths",
        authors: "Authors",
        courseDetail: "Course detail",
        listCourse: "List courses",
        ratingCourse: "Rating course",
        noDownload: "No downloads",
        noDownloadNoti: "Courses you download will appear here",
        recentSearches: "Recent searches",
        clearAll: "CLEAR ALL",
        follow: "FOLLOW",
        student: "student",
        course: "Course",
        courseSingle: "course",
        courseMany: "courses",
        instructor: "Instructor",
        result: "result",
        results: "results",
        trailer: "Trailer",
        trailerUpdating: "Trailer (updating)",
        coursesLikeCategory: "Courses like category",
        video: "video",
        videos: "videos",
        lesson: "Lesson",
        lessonSingle: "lesson",
        section: "Section",
        enroll: "Enroll",
        enrolled: "Enrolled",
        share: "Share",
        rate: "Rate",
        rating: "rating",
        ratingFromStudent: "Rating from students",
        likeCourse: "Like",
        likedCourse: "Liked",
        formalityPoint: "formality point",
        contentPoint: "content point",
        presentationPoint: "presentation point",
        formalityPointUpcase: "Formality point",
        contentPointUpcase: "Content point",
        presentationPointUpcase: "Presentation point",
        followRecommendation: "Follow to be notified when new courses are published",
        progress: "Your Progress",
        totalActiveDay: "TOTAL ACTIVE DAYS",
        mostActiveTime: "MOST ACTIVE TIME OF DAY",
        mostViewedSub: "MOST VIEWED SUBJECT",
        requireWifi: "Require Wi-Fi for downloading",
        majorUpdating: "Major updating",
        introUpdating: "Intro updating",
        courseUpdating: "Course updating",
        updating: "updating",
        learnWhat: "Learn what",
        requirement: "Requirement",
        description: "Description",
        rateCourseSuccess: "Rating course successfully",
        checkMailRequest: "Please check your email.",
        enrollCourseRequest: "Do you want to enroll this course?",
        signUpSuccess: "Sign up successfully. Please confirm in your mail",
        emailPassInvalid: "Email or password is invalid",
        emailInvalid: "Email invalid",
        notEmailFormat: "Email does not match with email format",
        passConfirmPassNotMatch: "Password and confirm password do not match",
        lengthPassRequest: "Password length must between 8 and 20",
        plsEnter:"Please enter ",
        editProfileSuccess: "Edit profile successfully",
        EDITPROFILE: "EDIT PROFILE",
        CHANGEPASS: "CHANGE PASSWORD",
        nameSingle: "name",
        phoneSingle: "phone",
        OK: "OK",
        CANCEL: "CANCEL",
        ALL: "ALL",
        INSTRUCTORS: "INSTRUCTORS",
        COURSES: "COURSES",
        darkTheme: 'Dark theme',
        lessonDetail: 'lessonDetail'
    }

export default Strings;