const 
Strings = {
    splashScreen: "Splash Screen",
    logIn: "Log In",
    register: "Register",
    forgotPassword: "Forgot password",
    verifyPassword: "Verify password",
    mainTabNavigation: "Main tab navigation",
    home: "Home",
    download: "Download",
    favorite: "Favorite",
    browse: "Browse",
    search: "Search",
    courses: "Courses",
    profile: "Profile",
    settings: "Settings",
    sendFeedback: "sendFeedback",
    recommendation: "Recommendation",
    category: "Category",
    skills: "Skills",
    paths: "Paths",
    authors: "Authors",
    courseDetail: "Course detail",
    noDownload: "No downloads",
    noDownloadNoti: "Courses you download will appear here",
    recentSearches: "Recent searches",
    clearAll: "CLEAR ALL",
    follow: "FOLLOW",
    followRecommendation: "Follow to be notified when new courses are published",
    progress: "Your Progress",
    totalActiveDay: "TOTAL ACTIVE DAYS",
    mostActiveTime: "MOST ACTIVE TIME OF DAY",
    mostViewedSub: "MOST VIEWED SUBJECT",
    requireWifi: "Require Wi-Fi for downloading",
    darkTheme: 'Dark theme'
}

export default Strings;